import StationModel from '../../model/StationModel';

export const DEFAULT_STATIONS: StationModel[] = [
  new StationModel(1, '🎸Heavy Metal', 's4-webradio.antenne.de/heavy-metal'),
  new StationModel(2, '💎Dance UK', 'boxstream.danceradiouk.com/stream'),
  new StationModel(3, '🎧 HiphopRapFM', 'ny.mysonicserver.com:8002/stream'),
  new StationModel(4, '⸸ Antenne Bayern', 's2-webradio.antenne.de/antenne'),
  new StationModel(5, '💎 Blues Radio', 'i4.streams.ovh:8352/stream'),
  new StationModel(6, '𓃶 Sumadinac FM', 'media.srb-streaming.com:8020/stream'),
  new StationModel(7, '🎸Heavy Metal', 's4-webradio.antenne.de/heavy-metal'),
  new StationModel(8, '💎 Dance UK', 'boxstream.danceradiouk.com/stream'),
  new StationModel(9, '🎧 HiphopRapFM', 'ny.mysonicserver.com:8002/stream'),
  new StationModel(10, '⸸ Antenne Bayern', 's2-webradio.antenne.de/antenne'),
  new StationModel(11, '💎 Blues Radio', 'i4.streams.ovh:8352/stream'),
  new StationModel(12, '𓃶 Sumadinac FM', 'media.srb-streaming.com:8020/stream')
];